SELECT * FROM barang WHERE HARGA_SATUAN > 10000 ORDER BY HARGA_SATUAN ASC;

SELECT * FROM pelanggan WHERE NAMA LIKE '%g%';

SELECT transaksi.KODE, transaksi.TANGGAL, pelanggan.NAMA AS NAMA_PELANGGAN, BARANG.NAMA AS NAMA_BARANG, transaksi.JUMLAH_BARANG AS JUMLAH, barang.HARGA_SATUAN, (transaksi.JUMLAH_BARANG * barang.HARGA_SATUAN) AS TOTAL
FROM transaksi
LEFT JOIN pelanggan 
ON transaksi.KODE_PELANGGAN = pelanggan.KODE
LEFT JOIN barang
ON transaksi.KODE_BARANG = barang.KODE
ORDER BY pelanggan.NAMA_PELANGGAN;

SELECT pelanggan.NAMA AS NAMA_PELANGGAN, 
(SELECT SUM(transaksi.JUMLAH) FROM transaksi LEFT JOIN PELANGGAN ON transaksi.KODE_PELANGGAN = pelanggan.KODE WHERE transaksi.KODE_PELANGGAN = pelanggan.KODE),
(SELECT transaksi.JUMLAH_BARANG * barang.HARGA_SATUAN AS TOTAL_HARGA FROM transaksi LEFT JOIN PELANGGAN ON transaksi.KODE_PELANGGAN = pelanggan.KODE LEFT JOIN barang ON transaksi.KODE_BARANG = barang.KODE WHERE transaksi.KODE_PELANGGAN = pelanggan.KODE),
